# Generated by Django 5.0.1 on 2024-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operation', 'verbose_name_plural': 'Operations'},
        ),
    ]
