# Generated by Django 5.0.1 on 2024-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_operation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='seperated_money',
            new_name='money',
        ),
        migrations.AddField(
            model_name='investor',
            name='action',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderartsiyada', 'Moderartsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Moderatsiyada', max_length=30),
        ),
    ]
